#!/usr/bin/ruby
require 'drb'
require 'digest'
require 'timeout'

options = ''
while ARGV[0]=~/^-/
  options += ARGV.shift
end

begin

  salt = File.read(File.expand_path('~/.cache/remote_system_call/salt')).strip
  uri  = File.read(File.expand_path('~/.cache/remote_system_call/connect')).strip
  drb  = DRbObject.new_with_uri(uri)

  pwd = `zenity --entry --text=Password --hide-text`.strip
  salted = Digest::SHA256.hexdigest("#{salt}#{pwd}")

  nonce = Time.now.to_i - 1
  digest = Digest::SHA256.hexdigest("#{nonce}#{salted}")
  commands = nil
  Timeout::timeout(3.0) do
    commands = drb.execute(nonce, digest, 'commands')
  end

  unless command = ARGV.shift
    list = commands.keys.sort.join(' ')
    command = `zenity --list --text='Command:' --column 'Command:' #{list}`.strip
  end

  if command.length > 0
    match = /^.*\$(\d)/.match(commands[command])
    arity = (match)? match[1].to_i : 0
    if ARGV.empty? and arity  > 0
      `zenity --entry --text=Arguments`.strip.split(/\s+/).each{|arg| ARGV.push(arg)}
    end
    raise "Args length #{ARGV.length} vs. command arity #{arity}" unless ARGV.length == arity

    nonce = Time.now.to_i
    digest = Digest::SHA256.hexdigest("#{nonce}#{salted}")
    response = drb.execute(nonce, digest, command, *ARGV)

    response = response.to_s.strip.gsub(/'/, '').gsub(/\s+/, ' ')
    system("zenity --info --text='#{response}'")
  end

rescue Exception
  # In case anybody is watching STDERR:
  STDERR.puts $!
  STDERR.puts $!.backtrace if options=~/-v/
  type = $!.class
  type = 'ValidationError' if type=~/Unknown/i
  system("zenity --error --text='#{type}'")
  exit 1
end
